### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by xcompass** [ubc/iPeer#290]
**Reported by DarkFulgoreII@gmail.com on 18 Apr 41469747 15:49 UTC**
Hi. I'm trying to follow the installation step on the site. Thats the problem: The install script are not on zip installation file. 
This is the file list on the ipeer directory on my server

VERSION.txt
app/
cake/
index.php
ipeer_export/
readme.txt
vendors/

The installation instructions tell me "browse http://your-domain.com/ipeer-dir/install" but there isn't a install folder or file on this directory, this step results on 404 error.

Thanks...

**Comment by pkovacs19** [comment]
Hello,

I am having this exact issue.  I am using iPeer-3.3.3 running on Centos7 server with PHP 5.4.

I do not see any "install" folder there, what am I missing?  

The only install files I can see are located at /app/views/install

Any help would be greatly appreciated!

Cheers,
Paul
