### ISSUE TITLE
Ability to export and import events by CSV files

### ISSUE THREAD

**Issue by gondek** [ubc/iPeer#491]
The feature would help with courses that have a large number of events (eg. some UBC CHBE courses have 40) that would need to be rolled over into a new course with some minor changes (eg. dates, descriptions, groups assigned).

Editing the events locally with a program (as opposed to an in-browser rollover feature) would be preferred because it allows for easy table navigation in a spreadsheet program (eg. batch copy and pasting event descriptions, close dates, etc).

**Comment by xcompass** [comment]
@andrew-gardener could you verify this feature? Thanks

**Comment by andrew-gardener** [comment]
Added #520
