### ISSUE TITLE
missing courses on home page for facultyadmin (RARE case)

### ISSUE THREAD

**Issue by mwytang** [ubc/iPeer#495]
If a faculty admin has administrative access to Faculty A and teaches course(s) in Faculty B, the list of courses of that will appear on their homepage will not include the courses in Faculty B. The reason is currently the implementation assumes faculty admins only have access to courses within faculties they have administrative access and not consider the situation where they teach in another faculty.

This is a very rare case, because this "error" will NOT happen if the faculty admin teaches in the faculties they have admin access in.

**Comment by xcompass** [comment]
I believe this issue is fixed now.
