### ISSUE TITLE
Forward UBC Instructors to Create Courses in Connect

### ISSUE THREAD

**Issue by gondek** [ubc/iPeer#505]
New UBC iPeer users (and some previous ones), end up creating a course through iPeer and then get confused about how to import users, groups etc. After getting help or reading the wiki, they end up creating a new course via Connect (leaving the original "empty" course) or link the courses together through Connect.

A notice to create the course from Connect could be put up to save the user and support staff time. This could be a simple UBC-only change or there could be a system parameter to enable/disable this warning.

**Comment by xcompass** [comment]
@andrew-gardener Could you implement something on the course creating page to show some information about the creating the course? The information can be stored in the system parameters table and turned off when the value is empty. I'm also open to other ideas.

**Comment by andrew-gardener** [comment]
Where are teachers getting information on how to do this now? 

It might be better to add link to system parameters instead of instructions directly (since it could be better formatted than a blob of text). This might also make it more usable to other users of iPeer.
