### ISSUE TITLE
Cake console i18n task doesn't complete

### ISSUE THREAD

**Issue by ijaureguialzo** [ubc/iPeer#508]
When using the cake console i18n task to extract .pot file for translation, the process stops without error at line:

```
Processing /.../iPeer/app/vendors/excel/PHPExcel/Shared/PDF/tcpdf.php...
```

but no output file is produced.

If I remove the vendor directory, the process ends and the .pot file is generated without error.

**Comment by xcompass** [comment]
Looks like we should exclude that file or vendor directory.

**Comment by xcompass** [comment]
@ijaureguialzo This is fix. You should be able to use `phing extract` to do the extraction in the future.

**Comment by ijaureguialzo** [comment]
Just tried and it's working. Thank you.
