### ISSUE TITLE
Willing to help with iPeer translation

### ISSUE THREAD

**Issue by ijaureguialzo** [ubc/iPeer#509]
Hello, I'm translating iPeer into Spanish for using with my students and I've been able to translate the strings currently available on the project, but I've found some pitfalls that make the task very hard to accomplish:

- Most of the strings are hardcoded in the templates, they can't be extracted because the lack of __() function use when displaying messages.
- There is no browser language detection or manual selection mechanism (had to change it in source to test). 
- The i18n task on CakePHP doesn't work (opened another issue on this).

My current progress is in this fork: https://github.com/ijaureguialzo/iPeer

I could help translating, cleaning PHP and template code. If there is no major code rewriting in the works, I will begin submitting pull request to the templates with the __()'s added.

BTW: CakePHP 1.3.x's __() function is a pain, because it doesn't return the string if no true parameter is added (took me a while to figure :). Is there any plan to upgrade CakePHP to a newer version?

**Comment by xcompass** [comment]
Thanks for the comments. We are thinking to completely rewrite iPeer using Symfony. However, due to the limited resources, the process is very slow right now. But in the new version, we will be able to address a lot of current issues we have right now, including the ones you pointed out.

**Comment by ijaureguialzo** [comment]
Great news, we have experience with Symfony and could help with the development. I'll stay tuned.
