### ISSUE TITLE
Hack: Minor Student Grade Manipulation

### ISSUE THREAD

**Issue by Spydude84** [ubc/iPeer#534]
This is about a potential security vulnerability within the iPeer system.

Regarding iPeer grading security, I was looking through the HTML code on the peer reviewing page while I was conducting a Peer review and I found something out of the ordinary.

Let’s start with some background context:
The scheme was a Rubric evaluation for one of my courses. There were 5 levels of Evaluation. 1) Unacceptable gave a mark of 1. 2) Emerging gave a mark of 2. 3) Marginally acceptable gave a mark of 3. 4) Accomplished gave a mark of 4. 5) Exemplary gave a mark of 5. 

So far pretty straight forward. What I found interesting was that I was able to manually edit these values to be something like 10, 1000, etc. I did not try it with negative values, but I assume that they would work the same. The specific value I tested with was 10. For one of the questions I replaced the 5 that I was originally going to give them with a 10 which was not only higher than the maximum of 5, but also pushed their total mark higher than the possible 20 marks available (A total of 22/20). I then tried to submit it and the system actually accepted this modified value. I then reentered the application to check to see if the 10 was actually saved and sure enough there it was.

This could potentially allow some students to boost their overall iPeer grade (if they were expecting negative reviews by their peers), to lower the students' grades they were reviewing (by giving negative values to their peers), or even to possibly completely boost their course grade by putting in absurd values (like 1000000000000000000000000000) to give them over 100% for iPeer evaluation. I know that this last one depends on the particular course as my instructor assured me that getting over 100% for iPeer in his course was impossible.

I have been in contact with the folks running iPeer and they suggested that I post this here.

I would like to say that although I am a student and though I could have used this for nefarious purposes, I refrained from doing so and made sure all values were reset to normal parameters before submitting the final version for marking. No academic dishonesty or fraud was committed. 
I am committed to helping improve the security of the internet which is a far better goal than some risky fraud related academic gains.

-Spydude.

Note: I hope that this description is not too long. I try to be thorough. I can take it down / minimize it if need be. There were some pictures, but they were not included here. The pictures were sent to the folks at iPeer though.

**Comment by andrew-gardener** [comment]
Thank you @Spydude84. #533 should fix this issue

**Comment by andrew-gardener** [comment]
The issue should be left open until the pull request is accepted (reviewed, pulled into master branch). Thanks

**Comment by Spydude84** [comment]
Sorry, not quite sure how things worked around here. Thanks for reopening!
