### ISSUE TITLE
Improve UI/UX to look more modern

### ISSUE THREAD

**Issue by wynnset** [ubc/iPeer#539]
iPeer's look is quite outdated. Let's make it more modern, and also try and improve the UX while doing it.

**Comment by lenglund** [comment]
Note that if we're planning to address UX, this should include actual users in some capacity (meaning we do research through interviews, focus groups, usability testing, etc.).

**Comment by wynnset** [comment]
@lenglund there were some obvious best practices that I applied for now ("low-hanging fruit") such as fixing spacing, desaturating colors and backgrounds a bit, etc. These didn't really require user feedback. I definitely agree with you on the bigger picture to fully address the UX issues and if you'd like to extend this task to bring feedback from users, that would be fantastic! The application definitely needs it.
