### ISSUE TITLE
Link / import courses from Canvas

### ISSUE THREAD

**Issue by kitsook** [ubc/iPeer#544]
If user’s iPeer profile has OAuth2 linked with Canvas, they will be able to select a course from Canvas and link it with a course in iPeer.  User also has the option to import the Canvas course as a new course in iPeer.

**Comment by kitsook** [comment]
Generate a list of active Canvas courses that the user has access to: `/api/v1/courses?enrollment_type=teacher`
-	Sort by
o	Start date in descending
o	Course code in ascending

iPeer DB changes:
-	New column `courses.canvas_course_id`

If linking with an existing iPeer course, only the canvas_course_id field will be updated.  If new iPeer course needs to be created:

  | iPeer   $this->Course->save() data | iPeer DB | Canvas REST API | Example / Remarks
-- | -- | -- | -- | --
  |   | courses.id | Auto generated in iPeer |  
Course subject /   number | data[Course][course] | courses.course | `/api/v1/courses?enrollment_type=teacher`       Extract from the field { “course_code” }??? | CPSC 101
Course Title | data[Course][title] | courses.title | `/api/v1/courses?enrollment_type=teacher`       Extract from the field { “name” } | Connecting with Computer Science
Instructors | data[Course][instructors] | user_courses | `/api/v1/courses/1/users?enrollment_type[]=teacher&include[]=enrollments`       The “include[]=enrollments” is probably not needed.  Can use the received “sis_user_id” / “integration_id”   / “sis_login_id” |  
Tutors | data[Course][tutors] | user_tutors | `/api/v1/courses/1/users?enrollment_type[]=ta&include[]=enrollments`       The “include[]=enrollments” is probably not needed.  Can use the received “sis_user_id” / “integration_id”   / “sis_login_id” |  
Status | data[Course][record_status] | courses.record_status | ~~Active (“A”):   if (either { “start_at” } or { “end_at” } is not null) and current date is between { “start_at” } and { “end_at” } else check { “workflow_state”” } is “available”. Otherwise Inactive (“I”)~~ Always set as "A". | Active / Inactive
Department | data[Department][Department] | course_departments | Don’t include in the Course->save() call.  Instead, assign department based on   instructors’ faculties (refer to courses_controllers.php) | CPSC
Homepage | data[Course][homepage] | courses.homepage | The course page on Canvas??? | http://mycoursehome.com
Linked Canvas course |   | courses.canvas_course_id |   |  
  | N/A | courses.self_enroll |   |  
  | N/A | courses.password |   |  
  | N/A | courses.creator_id |   |  
  | N/A | courses.created |   |  
  | N/A | courses.updater_id |   |  
  | N/A | courses.modified |   |

**Comment by wynnset** [comment]
Already done.
