### ISSUE TITLE
Synchronize data between Canvas and iPeer

### ISSUE THREAD

**Issue by kitsook** [ubc/iPeer#545]
When a pair of iPeer and Canvas courses are linked:

- User can import student list from Canvas into iPeer (one way only).  If students enrolled the course in iPeer but not in Canvas, user can choose (1) to keep the students in the iPeer course; or (2) take the Canvas list as the latest one.
- User can synchronize groups between Canvas and iPeer (two-way sync. User can choose to push from iPeer to Canvas or the other way around).  Since the student list between iPeer and Canvas may not be in sync, before the group synchronization, iPeer should retrieve the Canvas student list and compare first.  Display warning if necessary.

**Comment by wynnset** [comment]
Already done.
