### ISSUE TITLE
Synchronization of instructors and TAs with Canvas

### ISSUE THREAD

**Issue by kitsook** [ubc/iPeer#554]
- need to sync instructors and TAs

**Comment by wynnset** [comment]
When creating a course based on a Canvas course:

Import Instructors:
- Import with "instructor" system role
- Assign as instructor for the course

Import TAs:
- Import with "student" system role
- Assign as instructor for the course

Before starting on this, ensure the method above will work for imported TAs:
- Ensure TA will be able to see everything within the assigned course (same as instructor)
- Ensure TA cannot create a course or do other admin functionality.

**Comment by kitsook** [comment]
With system role as `student` and course role as `instructor`, the user can't access the `/courses` page.  Thus the user can't create events or manage groups.  Also, this kind of role setup is not support by the current `users` page.  @xcompass Either we need to revise the current logic or introduce a new `TA` role.
