### ISSUE TITLE
Improve iPeer Canvas Integration Course Name Display

### ISSUE THREAD

**Issue by timkato** [ubc/iPeer#598]
When syncing the course roster or groups for the first time from Canvas to iPeer, displaying the Canvas Course Name is not enough, please also show the Canvas Course Term so that instructors know which course is which if they teach the same course in multiple terms/years. Could also consider hiding concluded/old courses. ServiceNow ENHC0011669

**Comment by timkato** [comment]
Could also consider hiding concluded/old courses

**Comment by kitsook** [comment]
The existing logic should exclude concluded courses already.  Please let me know if this is not the case in production.

A pending change will append the course term after the course name (when creating new iPeer course from Canvas course, importing new users, and importing groups), e.g.

![image](https://user-images.githubusercontent.com/13360325/48653293-1ed07680-e9b9-11e8-8162-6cdf39cebda1.png)
