### ISSUE TITLE
v3.4 email issues

### ISSUE THREAD

**Issue by PhilCotton** [ubc/iPeer#615]
sending email via ipeer - right click on a user and selecting send email.  

version 3.1.9 returns a form, version 3.4 does not show the form.  

![ipeer3 1 9](https://user-images.githubusercontent.com/48366536/58645773-987ee080-82c9-11e9-8096-d70f465fe667.jpg)

![ipeer 3 4](https://user-images.githubusercontent.com/48366536/58645726-856c1080-82c9-11e9-9c82-5f9e91658a9c.jpg)

**Comment by PhilCotton** [comment]
made the changes on my end and the email form now shows.

**Comment by kitsook** [comment]
@PhilCotton Thanks for reporting the bug to us and confirming that the fix works.
