### ISSUE TITLE
Canvas assignment API changes

### ISSUE THREAD

**Issue by kitsook** [ubc/iPeer#622]
A Canvas [API change](https://canvas.instructure.com/doc/api/file.breaking.html) will remove the `muted` parameter from the [Assignment Creation API](https://canvas.instructure.com/doc/api/assignments.html#method.assignments_api.create).

iPeer sets this parameter to true when creating a new assignment on Canvas so that the assignment is hidden on gradebook.  Will need code change before the parameter is deprecated (Jan 2020).

https://github.com/ubc/iPeer/blob/53bbb6290d88d4e684d49766f16b39963c8ae2aa/app/controllers/evaluations_controller.php#L505-L514

**Comment by kitsook** [comment]
Initial analysis.  With the new gradebook, instead of using the deprecated `muted` parameter to hide grades, [there are three ways](https://community.canvaslms.com/docs/DOC-17330-41521116619) to hide them.  The  "manual posting for an assignment" approach is probably the one we want: instructors need to manually release the synchronized grades on Canvas.

The corresponding Assignment attribute for this is `post_manually`.  However, this attribute is not listed as one of the parameters in Canvas Assignment API.  Need to test it out.

**Comment by kitsook** [comment]
Tried to change the assignment post policy using Canvas web UI.  It doesn't use the Assignment API at all.  Instead, it uses the new [Canvas Graph QL API](https://canvas.instructure.com/doc/api/file.graphql.html) (`POST` on `/api/graphql`):

```
{
  "operationName": "SetAssignmentPostPolicy",
  "variables": {
    "assignmentId": "xxxx",
    "postManually": true
  },
  "query": "mutation SetAssignmentPostPolicy($assignmentId: ID!, $postManually: Boolean!) {\n  setAssignmentPostPolicy(input: {assignmentId: $assignmentId, postManually: $postManually}) {\n    postPolicy {\n      postManually\n      __typename\n    }\n    errors {\n      attribute\n      message\n      __typename\n    }\n    __typename\n  }\n}\n"
}
```

**Comment by timkato** [comment]
Confirming that the "manual posting for an assignment" approach is best
