### ISSUE TITLE
Can't start installation wizard

### ISSUE THREAD

**Issue by pkovacs19** [ubc/iPeer#625]
Hello,

I am having this exact issue as #290 . I am using iPeer-3.3.3 running on Centos7 server with PHP 5.4.

I am at the point where I am to go to `<www.your-host.com>/<your-install-dir>/install`

 to start the installation wizard, but when I go there I am returned with a 404, "The requested URL /install was not found on this server."
I do not see any "install" folder there, the only install files I can see are located at app/views/install.  What am I missing?

I've unzipped the ipeer files to "/export/web/iPeer-3.3.3" which is also the root directory of the virtural host, so to my understanding, I should be able to get the install wizard to start up at `<www.your-host.com>/install`, is that correct?  If not thats probably what I'm doing wrong.  I have also tried `<www.your-host.com/export/web/iPeer-3.3.3/install`, which give the same 404.

Please let me know if you need any other information.  Any help would be greatly appreciated!

**Comment by kitsook** [comment]
Hi @pkovacs19. When first launched, no matter which app url you are trying to access, you should see the install wizard.  A few things to check:

- Have you configured the web virtual host correctly with PHP and root directory correctly?  Do you see any PHP error logs?

- Have u configured the db?  You can try the default settings by making a copy of `app/config/database.php.default` and name it as `app/config/database.php`

**Comment by pkovacs19** [comment]
Thanks for the help @kitsook.  I managed to get the installer to run.  The 2 issues I had were to make apache user the own of the ipeer content and I had to downgrade mysql version (I was using 8.0 initially) and got it to work with MariaDB 5.5
