### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by dramaley** [ubc/iPeer#633]
Hello! I am attempting to upgrade our iPeer test instance from 3.1.9 to 3.4.4. We're running on a Red Hat Enterprise Linux 7 box using the built-in software stack (MariaDB 5.5.64, PHP 5.4.16, Apache HTTPd 2.4.6). The upgrade instructions at http://ipeer.ctlt.ubc.ca/wiki/Upgrade seem rather outdated and i could not find anything newer. So i just unpacked the new version's tarball over the old installation, as we used to do.

Immediately after the update iPeer would not load and i saw "Database driver mysql is not supported!" in the Apache error_log. I then installed the mysqli package from RHEL and updated iPeer's app/config/database.php to set the driver to "mysqli". Now iPeer half-loads; when i browse to it i get a page that says "Error" in the title, but is not fully rendered. There are no errors in the Apache log. Any ideas what to do to get it working again?

If necessary, i made a snapshot of the machine prior to doing anything, so i can roll back to 3.1.9 if needed and do the upgrade in smaller steps.

**Comment by kitsook** [comment]
Hi @dramaley. iPeer 3.4+ requires PHP 7.2.

**Comment by dramaley** [comment]
Oh, thank you! I didn't know that 3.4 required a newer PHP. I was able to revert the server to the snapshot that was running iPeer 3.1.9. An upgrade to 3.3.3 was successful without problems.

Next month we're planning on moving that server to a new OS that has a newer PHP, so I'll try the iPeer 3.4.4 update again at that time.
