### ISSUE TITLE
Can't do integration test

### ISSUE THREAD

**Issue by belvin92** [ubc/iPeer#643]
Hi guys, 

Please advise as i came across this error message when trying to start the integration test in the docker container, please see attached screenshot.

I need to get the vendor/bin/phing/ test  command going in order for me to run /install iPeer through localhost:8080/install

![Screenshot from 2020-05-22 01-52-53](https://user-images.githubusercontent.com/64530566/82578409-b24abf00-9bcf-11ea-9179-422ebc4f4824.png)

**Comment by kitsook** [comment]
You don't need to run integration tests / unit tests for completing the installation.

Seems like your setup is missing the `app/config/database.php` file.

We added a [Quick Start](https://github.com/ubc/iPeer#quick-start) section to the readme file.  You may refer to it on how to setup a docker environment for trying out iPeer.
