### ISSUE TITLE
Changing from Port 8080 to Port 80 for iPeer

### ISSUE THREAD

**Issue by belvin92** [ubc/iPeer#652]
Hi Everyone,

I was wondering how to change the port from 8080 to 80?

I realise it is in docker-compose.yml but i am not sure what is the syntax to just change it to 80

**Comment by xcompass** [comment]
It is in https://github.com/ubc/iPeer/blob/master/docker-compose.yml#L56. You can change it to `80:80`. However, you will need root permission to run it after changing it to 80.

**Comment by belvin92** [comment]
Thanks.I gave that a go but on localhost it still displays the default page not iPeer

![Capture](https://user-images.githubusercontent.com/64530566/89450969-cf3e6980-d79e-11ea-81bc-64a7a09efa82.PNG)
