### ISSUE TITLE
Loading iPeer Issue

### ISSUE THREAD

**Issue by belvin92** [ubc/iPeer#654]
![image](https://user-images.githubusercontent.com/64530566/89777946-0078ba00-db50-11ea-9f0d-7b9795223566.png)

Hi all, i am trying to install iPeer on another machine and i manage to get to localhost:8080/install. After the installation, this appears on my screen indicating user is not found?

Please help

**Comment by xcompass** [comment]
It seems it is missing guard plugin. How did you install ipeer? Did you use docker-compose?

**Comment by belvin92** [comment]
Hi xcompass,

My apologies that was my mistake i didnt install composer within ipeer thats why it didnt had the guard plugin plus the vendor folders etc..

I will close this.
